from enum import StrEnum


class OrderStatus(StrEnum):
    """order-service의 Order 상태 계약을 미러링한다(내부 API로 수신하는 값)."""

    PENDING = "PENDING"
    STOCK_RESERVED = "STOCK_RESERVED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    COMPENSATION_FAILED = "COMPENSATION_FAILED"


class ShipmentStatus(StrEnum):
    """shipment-service의 Shipment 상태 계약을 미러링한다(내부 API로 수신하는 값).

    진행 중(살아있는) 상태: HUB_WAITING/HUB_MOVING/HUB_ARRIVED/COMPANY_MOVING.
    종료 상태: DELIVERED/CANCELLED.
    """

    HUB_WAITING = "HUB_WAITING"
    HUB_MOVING = "HUB_MOVING"
    HUB_ARRIVED = "HUB_ARRIVED"
    COMPANY_MOVING = "COMPANY_MOVING"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class TriggerType(StrEnum):
    USER_QUERY = "USER_QUERY"
    SYSTEM_INCIDENT = "SYSTEM_INCIDENT"
    SCHEDULED_SCAN = "SCHEDULED_SCAN"


class DiagnosisStatus(StrEnum):
    NORMAL = "NORMAL"
    FAILED_COMPENSATED = "FAILED_COMPENSATED"
    FAILED_COMPENSATION_FAILED = "FAILED_COMPENSATION_FAILED"
    MANUAL_INTERVENTION_REQUIRED = "MANUAL_INTERVENTION_REQUIRED"
    RISK_DETECTED = "RISK_DETECTED"
    UNKNOWN = "UNKNOWN"


class CompensationStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class FailureStep(StrEnum):
    ORDER_CREATION = "ORDER_CREATION"
    PRODUCT_VALIDATION = "PRODUCT_VALIDATION"
    INVENTORY_RESERVATION = "INVENTORY_RESERVATION"
    PRODUCT_HUB_LOOKUP = "PRODUCT_HUB_LOOKUP"
    RECIPIENT_HUB_LOOKUP = "RECIPIENT_HUB_LOOKUP"
    HUB_ROUTE_LOOKUP = "HUB_ROUTE_LOOKUP"
    SHIPMENT_CREATION = "SHIPMENT_CREATION"
    AI_ANALYSIS = "AI_ANALYSIS"
    SLACK_NOTIFICATION = "SLACK_NOTIFICATION"
    UNKNOWN = "UNKNOWN"


class ActionRiskLevel(StrEnum):
    READ_ONLY = "READ_ONLY"
    SAFE_WRITE = "SAFE_WRITE"
    RECOVERY_WRITE = "RECOVERY_WRITE"
    DANGEROUS_MANUAL = "DANGEROUS_MANUAL"


class ProposalStatus(StrEnum):
    """권장 조치 제안의 생애주기(design §12.4). 현재는 PROPOSED만 기록하고,
    APPROVED/REJECTED/EXECUTED는 후속 human-in-the-loop recovery에서 사용한다."""

    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"
