server:
  port: 8082

spring:
  application:
    name: hub-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: ${HUB_DB_URL:jdbc:postgresql://localhost:5432/sparta_logistics?currentSchema=hub_db}
    username: ${DB_USERNAME:sparta}
    password: ${DB_PASSWORD:sparta1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hub_db
    show-sql: false
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis1234}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    root: INFO
    com.sparta.whereismyparcel: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
