server:
  port: 8084

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      discovery:
        enabled: true
        service-id: config-server
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/sparta_logistics?currentSchema=order_db}
    username: ${DB_USERNAME:sparta}
    password: ${DB_PASSWORD:sparta1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: order_db
    show-sql: false
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
