spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: hub-service
        url: /v3/api-docs/hub-service
      - name: company-service
        url: /v3/api-docs/company-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: shipment-service
        url: /v3/api-docs/shipment-service
      - name: ai-slack-service
        url: /v3/api-docs/ai-slack-service
